directory: ~/sound
library: ~/.config/beets/library.db

import:
    copy: no
ui:
    color: yes

plugins: replaygain edit smartplaylist mpdupdate

replaygain:
    backend: gstreamer

smartplaylist:
    relative_to: ~/sound
    playlist_dir: ~/.mpd/playlists
    playlists:
        - name: full.m3u
          query: 'albumartist+ year+ album+ track+'
        - name: latest-first.m3u
          query: 'added-'
