directory: ~/sound
library: ~/.config/beets/library.db

import:
    copy: no
ui:
    color: yes

plugins: replaygain edit smartplaylist mpdupdate follow

replaygain:
    backend: gstreamer

follow:
  auto: yes
  email: justfdot@gmail.com
  password: myopenpassword
  userid: 2hdgnu0i19k66fuqpf8k25xl9qpbjp

smartplaylist:
    relative_to: ~/sound
    playlist_dir: ~/.mpd/playlists
    playlists:
        - name: full.m3u
          query: 'albumartist+ year+ album+ track+'
        - name: latest-first.m3u
          query: 'added-'
