#!/usr/bin/env bash

sources_dir="/usr/src/linux"

kernel_in_use=$(uname -r)
kernel_to_update=$(readlink "$sources_dir")
kernel_to_update=${kernel_to_update#linux-}

typeset -A format
format=(
    [green]=$(tput setaf 10)
    [red]=$(tput setaf 9)
    [bold]=$(tput bold)
    [reset]=$(tput sgr 0)
)

header () {
    echo -e "\n ${format[red]}*${format[reset]} $1\n"
}

info () {
    echo -e " ${format[green]}*${format[reset]} $1"
}

header "Updating kernel from ${format[bold]}$kernel_in_use${format[reset]} to ${format[bold]}$kernel_to_update${format[reset]}"

info "Mount /boot"
mount /dev/sda2 /boot

info "Copy current kernel config"
cp /boot/config-"$kernel_in_use" /usr/src/linux/.config
cp /boot/config-"$kernel_in_use" ~/kernel-config-"$kernel_in_use"

info "Compile kernel:"
cd "$sources_dir" || { echo "Couldn't get directory $sources_dir"; exit 1; }
info "[1/5] make olddefconfig"
make -j9 olddefconfig > /dev/null
info "[2/5] make modules_prepare"
make -j9 modules_prepare > /dev/null
info "[3/5] make"
make -j9 > /dev/null
info "[4/5] make modules_install"
make -j9 modules_install > /dev/null
info "[5/5] make install"
make install > /dev/null

info "Update grub config"
grub-mkconfig -o /boot/grub/grub.cfg

info "Remove source files of ${format[bold]}$kernel_in_use${format[reset]} kernel"
emerge -P gentoo-sources
rm -rf /usr/src/linux-"$kernel_in_use"

info "Cleanup old files"
for FILE in $(find /lib/modules -maxdepth 1 -mindepth 1 -type d -printf '%f\n' | sort -V | head -n -3); do
  rm -rf "/boot/{vmlinuz,System.map,config}${FILE:?}"
  rm -rf "/lib/modules/${FILE:?}"
done

info "Unmount /boot"
umount /boot

info "Rebuild depending on kernel modules"
emerge @module-rebuild

header "Kernel ${format[bold]}$kernel_to_update${format[reset]} is now installed"
